# Default values for dawarich.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: docker.io/freikin/dawarich
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

env:
  minMinutesSpentInCity: "60"
  applicationHost: "dawarich.example.org"
  timeZone: "Europe/Berlin"
  backgroundProcessingConcurrency: "10"
  applicationProtocol: "http"
  distanceUnit: "km"
  photonApiHost: "photon.komoot.io"
  photonApiUseHttps: "true"

dawarich:
  replicaCount: 1

  # This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
  livenessProbe:
    httpGet:
      path: /api/v1/health
      port: http
  readinessProbe:
    httpGet:
      path: /api/v1/health
      port: http
  startupProbe:
    httpGet:
      path: /api/v1/health
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 10

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 256Mi
    # requests:
    #   cpu: 500m
    #   memory: 2Gi

  nodeSelector: {}

  tolerations: []

  affinity: {}

sidekiq:
  replicaCount: 1

  # This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
  livenessProbe:
    exec:
      command:
        - "sh"
        - "-c"
        - "bundle exec sidekiqmon processes | grep ${HOSTNAME}"
  readinessProbe:
    exec:
      command:
        - "sh"
        - "-c"
        - "bundle exec sidekiqmon processes | grep ${HOSTNAME}"
  startupProbe:
    exec:
      command:
        - "sh"
        - "-c"
        - "bundle exec sidekiqmon processes | grep ${HOSTNAME}"
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 10

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 256Mi
    # requests:
    #   cpu: 500m
    #   memory: 2Gi

  nodeSelector: {}

  tolerations: []

  affinity: {}

persistence:
  gemCache:
    enabled: true
    existingClaim: ""
    annotations: []
    accessMode: "ReadWriteOnce"
    storageClass: ""
    size: 1Gi
  public:
    enabled: true
    existingClaim: ""
    annotations: []
    accessMode: "ReadWriteOnce"
    storageClass: ""
    size: 10Gi
  watched:
    enabled: true
    existingClaim: ""
    annotations: []
    accessMode: "ReadWriteOnce"
    storageClass: ""
    size: 10Gi

postgresql:
  auth:
    # Either set the postgresql credentials in the helm chart, or provide your own secret.
    database: dawarich
    password: changeme
    username: dawarich
    # existingSecret: dawarich-postgresql
  primary:
    persistence:
      enabled: false
      # storageClass: ""
      # size: 8Gi
    # https://github.com/Freika/dawarich/pull/569
    extendedConfiguration: |-
      shared_buffers = 512MB
      work_mem = 128MB
      maintenance_work_mem = 128MB
      max_wal_size = 1GB
      min_wal_size = 80MB
      max_parallel_workers_per_gather = 4
  shmVolume:
    # As per upstream
    sizeLimit: 1Gi

redis:
  auth:
    enabled: true
    password: changeme
    # Use an existing secret for redis auth. Do this if you're using Argo to manage your instance or otherwise using helm template under the hood
    #     The secret name can vary, but the password key must be redis-password.
    # existingSecret: dawarich-redis-secret
  master:
    persistence:
      enabled: false
  replica:
    replicaCount: 0

# This is for the secretes for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 3000

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# Additional volumes on the output Deployment definition.
extraVolumes: []

# Additional volumeMounts on the output Deployment definition.
extraVolumeMounts: []
