{{- if not .Values.keyBase.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dawarich.fullname" . }}-secret-keybase
  labels:
    {{- include "dawarich.labels" . | nindent 4 }}
type: Opaque
stringData:
  value: {{ .Values.keyBase.value }}
{{- end }}
