apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dawarich.fullname" . }}
  labels:
    {{- include "dawarich.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "dawarich.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dawarich.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dawarich.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{ include "dawarich.initContainers" . | nindent 10 }}
      containers:
        - name: {{ .Chart.Name }}
          command: ['sh', '-c', 'dev-entrypoint.sh bin/dev']
          envFrom:
            {{- include "dawarich.envFrom" . | nindent 12 }}
          env:
            {{- include "dawarich.env" . | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- include "dawarich.volumeMounts" . | trim | nindent 12 }}
        - name: {{ .Chart.Name }}-sidekiq
          command: ['sh', '-c', 'dev-entrypoint.sh sidekiq']
          envFrom:
            {{- include "dawarich.envFrom" . | nindent 12 }}
          env:
            {{- include "dawarich.env" . | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- include "dawarich.sidekiqVolumeMounts" . | trim | nindent 12 }}
          {{- end }}
      volumes:
        {{- include "dawarich.volumes" . | trim | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
