{{- if not .Values.dawarich.redis.url }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "dawarich.fullname" . }}-redis
  labels:
    {{- include "dawarich.labels" . | nindent 4 }}
data:
  REDIS_URL: "redis://redis:{{ .Values.dawarich.redis.password }}@redis:6379/0"
{{- end }}
