{{- if and .Values.persistence.storage.enabled (not .Values.persistence.storage.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "dawarich.fullname" . }}-storage
  labels:
    app.kubernetes.io/name: {{ include "dawarich.name" . }}
    helm.sh/chart: {{ include "dawarich.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.persistence.storage.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.storage.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.storage.size | quote }}
  {{- with .Values.persistence.storage.storageClass }}
  {{- if (eq "-" .) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ . }}"
  {{- end }}
  {{- end }}
{{- end }}
